---
title: TPC6 – turma 2 - Resolução
author: André Plancha - CDB2 - 105289
date: versão 1.0 - 05/10/2022
subject: TPC6 - turma 2
header-includes:
 - \usepackage{xfrac}
 - \usepackage{comment}
 - \usepackage{amsmath}
 - \usepackage{siunitx}
 - \newcommand{\unaryminus}{\scalebox{0.5}[1.0]{\( - \)}}
 - \usepackage{interval}
 - \newcommand{\indep}{\perp \!\!\! \perp}
# - \usepackage[cp1251]{inputenc}
listings-disable-line-numbers: true
listings-no-page-break: true
output:
pdf_document:
toc: false
number_sections: false
---

> Suponha a experiência aleatória que consiste em fazer scroll, sem qualquer regra, num
banco de fotos genéricas e contar quantas fotos de gatinhos vê em 5 minutos. Ou seja,
considere a seguinte variável aleatória X – número de fotos de gatinhos visionadas em 5
minutos. Assuma que está em condições de considerar X como tendo distribuição de Poisson
de parâmetro $\lambda$

A função de probabilidade de X é dada por:
```{=latex}
\begin{align}
f(k; \lambda) = P\{X = k \}= \frac{\lambda^k e^{-\lambda}}{k!}
\end{align}
```
, sendo $\lambda$ o número de fotos de gatinhos por \qty{5}{\minute}.

# a)

>  Construa a função de probabilidade conjunta de $(X_1, X_2, \dots , X_10)$.

Segundo a *regra da cadeia de probabilidade*, função de distribuição de probabilidade conjunta de 2 variáveis aleatórias $X_1, X_2$ é dada por:
```{=latex}
\begin{align}
p_{X,Y}(x,y) &=\mathrm {P} \{X=x \cap Y=y\} \\
             &=\mathrm {P} \{Y=y\mid X=x\}\cdot \mathrm {P} \{X=x\}=\mathrm {P} \{X=x\mid Y=y\}\cdot \mathrm {P} \{Y=y\}
\end{align}
```
. Esta regra é válida para qualquer número de variáveis aleatórias; ou seja:
```{=latex}
\begin{align}
p_{X_1, X_2, \dots, X_n}(x_1, x_2, \dots, x_n) &=\mathrm {P} \{X_1=x_1 \cap X_2=x_2 \cap \dots \cap X_n=x_n\}
\end{align}
```
Como a amostra é composta por variáveis aleatórias independentes e $\forall (X, Y) \in \mathbb{R}^2 \colon X \indep Y \Rightarrow P\{X \mid Y\} = P\{X\}$, a função de distribuição de probabilidade conjunta é dada por:
```{=latex}
\begin{align}
p_{X_1, X_2, \dots, X_n}(x_1, x_2, \dots, x_n) &=\mathrm {P} \{X_1=x_1\}\times \mathrm {P} \{X_2=x_2\}\times \dots \times \mathrm {P} \{X_n=x_n\} \\
&= \prod_{i=1}^{n} \mathrm {P} \{X_i=x_i\}
\end{align}
```
. Logo, a função de probabilidade conjunta de $\boldsymbol{X} = (X_1, X_2, \dots , X_{10})$ é dada por:
```{=latex}
\begin{align}
p_{\boldsymbol{X}}(\boldsymbol{x})
&= \prod_{i=1}^{10} \mathrm {P} \{X_i=x_i\} \\
&= \prod_{i=1}^{10} \frac{\lambda^{x_i} e^{-\lambda}}{x_i!}
\end{align}
```

# b)

> Se \lambda 